deploy

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -5,14 +5,9 @@ on:
     branches:
       - main
 
-permissions:
-  contents: read
-  secrets: read
-
 jobs:
   build-and-deploy:
     runs-on: ubuntu-latest
-
     steps:
       - name: Checkout code
         uses: actions/checkout@v3
@@ -20,10 +15,20 @@ jobs:
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v2
 
-      - name: Debug Secrets (remove after verifying)
+      - name: Check if secrets are set
         run: |
-          echo "DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}"
-          echo "DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}"
+          missing_secrets=()
+          for secret in DOCKERHUB_USERNAME DOCKERHUB_TOKEN POSTGRES_DB POSTGRES_USER POSTGRES_PASSWORD POSTGRES_HOST POSTGRES_PORT DJANGO_SECRET_KEY DJANGO_DEBUG DJANGO_SUPERUSER_USERNAME DJANGO_SUPERUSER_EMAIL DJANGO_SUPERUSER_PASSWORD RENDER_DEPLOY_HOOK
+          do
+            if [ -z "${{ secrets[secret] }}" ]; then
+              missing_secrets+=($secret)
+            fi
+          done
+          if [ ${#missing_secrets[@]} -ne 0 ]; then
+            echo "Error: The following secrets are not set: ${missing_secrets[*]}"
+            exit 1
+          fi
+        shell: bash
 
       - name: Login to Docker Hub
         uses: docker/login-action@v3
@@ -57,4 +62,8 @@ jobs:
         env:
           deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK }}
         run: |
+          if [ -z "$deploy_url" ]; then
+            echo "Error: RENDER_DEPLOY_HOOK is not set"
+            exit 1
+          fi
           curl -X POST $deploy_url
